---
- name: Create users 
  hosts: all
  var_files:
    - vars/users.yml
    
  tasks:
    - name: Create users
      user: 
        name: "{{ item.name }}"
        password: {{ item.password|password_hash('sha512') }}
        state: present
      with_items: {{ userslist }}
        
...
