---
- name: Create users 
  hosts: all
  vars_files:
    - vars/users.yml
    
  tasks:
    - name: Create users
      user: 
        name: "{{ item.name }}"
        password: "{{ item.password|password_hash('sha512') }}"
        comment: "{{ item.name }}@example.com"
        home: "/home/{{ item.name|lower }}"
        update_password: on_create
        state: present
      with_items: "{{ userslist }}"
        
...
